// <auto-generated />
using System;
using B1TestTask.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace B1TestTask.DataAccess.Migrations
{
    [DbContext(typeof(FirstTaskDbContext))]
    partial class FirstTaskDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.33")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("B1TestTask.Domain.Entities.FileLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("DoubleNumber")
                        .HasColumnType("double precision");

                    b.Property<int>("IntNumber")
                        .HasColumnType("integer");

                    b.Property<string>("LatinStr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MergedFileId")
                        .HasColumnType("integer");

                    b.Property<string>("RussianStr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MergedFileId");

                    b.ToTable("FileLines");
                });

            modelBuilder.Entity("B1TestTask.Domain.Entities.MergedFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("B1TestTask.Domain.Entities.FileLine", b =>
                {
                    b.HasOne("B1TestTask.Domain.Entities.MergedFile", "MergedFile")
                        .WithMany()
                        .HasForeignKey("MergedFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MergedFile");
                });
#pragma warning restore 612, 618
        }
    }
}
